name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: mvn clean verify -DskipTests=true --show-version
  test-with-server:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mattermost-version: [5.14.2, 5.9.4]
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306/tcp
        env:
          MYSQL_ROOT_PASSWORD: mostest
          MYSQL_USER: mmuser
          MYSQL_PASSWORD: mostest
          MYSQL_DATABASE: mattermost_test
      inbucket:
        image: jhillyerd/inbucket:release-2.0.0
        ports:
          - 2500/tcp
      mattermost:
        image: mattermost/mattermost-enterprise-edition:${{ matrix.mattermost-version }}
        ports:
          - 8065/tcp
        env:
          MM_SERVICESETTINGS_LISTENADDRESS: ":8065"
          MM_SQLSETTINGS_DRIVERNAME: mysql
          MM_SQLSETTINGS_DATASOURCE: mmuser:mostest@tcp(mysql:3306)/mattermost_test?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s
          MM_PLUGINSETTINGS_ENABLE: true
          MM_PLUGINSETTINGS_ENABLEUPLOADS: true
          MM_EMAILSETTINGS_SMTPSERVER: inbucket
          MM_EMAILSETTINGS_SMTPPORT: 2500
          MM_RATELIMITSETTINGS_ENABLE: false
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: mvn clean verify --show-version
        env:
          MATTERMOST_URL: http://localhost:${{ job.services.mattermost.ports['8065'] }}
          INBUCKET_HOST: inbucket
          INBUCKET_PORT: 2500
          USE_LOCAL_DUMMY_SERVER: false
          DUMMY_HTTP_SERVER_HOST: static.bis5.net
          DUMMY_HTTP_SERVER_PORT: 0
  test-with-server-old:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mattermost-version: [5.13.2, 5.12.5]
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306/tcp
        env:
          MYSQL_ROOT_PASSWORD: mostest
          MYSQL_USER: mmuser
          MYSQL_PASSWORD: mostest
          MYSQL_DATABASE: mattermost_test
      inbucket:
        image: jhillyerd/inbucket:release-2.0.0
        ports:
          - 2500/tcp
      mattermost:
        image: mattermost/mattermost-enterprise-edition:${{ matrix.mattermost-version }}
        ports:
          - 8000/tcp
        env:
          MM_SERVICESETTINGS_LISTENADDRESS: ":8000"
          MM_SQLSETTINGS_DRIVERNAME: mysql
          MM_SQLSETTINGS_DATASOURCE: mmuser:mostest@tcp(mysql:3306)/mattermost_test?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s
          MM_PLUGINSETTINGS_ENABLE: true
          MM_PLUGINSETTINGS_ENABLEUPLOADS: true
          MM_EMAILSETTINGS_SMTPSERVER: inbucket
          MM_EMAILSETTINGS_SMTPPORT: 2500
          MM_RATELIMITSETTINGS_ENABLE: false
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: mvn clean verify --show-version
        env:
          MATTERMOST_URL: http://localhost:${{ job.services.mattermost.ports['8000'] }}
          INBUCKET_HOST: inbucket
          INBUCKET_PORT: 2500
          USE_LOCAL_DUMMY_SERVER: false
          DUMMY_HTTP_SERVER_HOST: static.bis5.net
          DUMMY_HTTP_SERVER_PORT: 0
  sonarqube:
    needs: [test-with-server]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mattermost-version: [5.14.2]
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306/tcp
        env:
          MYSQL_ROOT_PASSWORD: mostest
          MYSQL_USER: mmuser
          MYSQL_PASSWORD: mostest
          MYSQL_DATABASE: mattermost_test
      inbucket:
        image: jhillyerd/inbucket:release-2.0.0
        ports:
          - 2500/tcp
      mattermost:
        image: mattermost/mattermost-enterprise-edition:${{ matrix.mattermost-version }}
        ports:
          - 8065/tcp
        env:
          MM_SERVICESETTINGS_LISTENADDRESS: ":8065"
          MM_SQLSETTINGS_DRIVERNAME: mysql
          MM_SQLSETTINGS_DATASOURCE: mmuser:mostest@tcp(mysql:3306)/mattermost_test?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s
          MM_PLUGINSETTINGS_ENABLE: true
          MM_PLUGINSETTINGS_ENABLEUPLOADS: true
          MM_EMAILSETTINGS_SMTPSERVER: inbucket
          MM_EMAILSETTINGS_SMTPPORT: 2500
          MM_RATELIMITSETTINGS_ENABLE: false
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: mvn clean verify sonar:sonar --show-version -s .circleci/settings-sonar.xml
        env:
          MATTERMOST_URL: http://localhost:${{ job.services.mattermost.ports['8065'] }}
          INBUCKET_HOST: inbuclet
          INBUCKET_PORT: 2500
          USE_LOCAL_DUMMY_SERVER: false
          DUMMY_HTTP_SERVER_HOST: static.bis5.net
          DUMMY_HTTP_SERVER_PORT: 0
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
